/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;


import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;




/**
 *
 * @author DIVYA
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REGISTRATION = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        contactno = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jaddress = new javax.swing.JTextField();
        jcontact = new javax.swing.JTextField();
        jpass = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        REGISTRATION.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        REGISTRATION.setForeground(new java.awt.Color(242, 242, 242));
        REGISTRATION.setText("REGISTRATION");
        getContentPane().add(REGISTRATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 280, -1));

        jname.setBackground(new java.awt.Color(0, 0, 0));
        jname.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jname.setForeground(new java.awt.Color(242, 242, 242));
        jname.setText("UserName");
        getContentPane().add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 111, -1));

        email.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        email.setForeground(new java.awt.Color(242, 242, 242));
        email.setText("Email");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, -1));

        contactno.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        contactno.setForeground(new java.awt.Color(242, 242, 242));
        contactno.setText("Contact ");
        getContentPane().add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 111, -1));

        address.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        address.setForeground(new java.awt.Color(242, 242, 242));
        address.setText("Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 111, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 258, -1));
        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 260, -1));

        jaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddressActionPerformed(evt);
            }
        });
        getContentPane().add(jaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 258, -1));
        getContentPane().add(jcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 258, -1));

        jpass.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jpass.setForeground(new java.awt.Color(242, 242, 242));
        jpass.setText("Password");
        getContentPane().add(jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, -1));
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 260, -1));

        submit.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 120, -1));

        back.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 479, 116, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaddressActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
         

          String username = jTextField1.getText();
                String password = new String(jpassword.getPassword());
                String address= jaddress.getText();
                 String email= jemail.getText();
                  String contact= jcontact.getText();
              
                if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill out Username");
        return;
    }
    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill out Password");
        return;
    }
        try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","sunny123");
              
             
             con.setAutoCommit(true);

                    String sql = "insert into user(username,password,email,Contact_no,Address)values(?,?,?,?,?)";
                     PreparedStatement pstmt = con.prepareStatement(sql);
                      pstmt.setString(1, username);
                      pstmt.setString(2, password);
                       pstmt.setString(3, address);
                       pstmt.setString(4, email);
                      pstmt.setString(5, contact);
                     
    int rowsInserted = pstmt.executeUpdate();

    System.out.println("Rows inserted: " + rowsInserted);

    if (rowsInserted > 0) {
        System.out.println("Insert successful");
        new Login().setVisible(true);
    } else {
        System.out.println("Insert failed");
        JOptionPane.showMessageDialog(this, "Registration canceled");
    }
        }catch(Exception e){
            e.printStackTrace(); 
        }

    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Titlepage().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel REGISTRATION;
    private javax.swing.JLabel address;
    private javax.swing.JButton back;
    private javax.swing.JLabel contactno;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jaddress;
    private javax.swing.JTextField jcontact;
    private javax.swing.JTextField jemail;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jpass;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
