/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

/**
 *
 * @author DIVYA
 */
public class Titlepage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Titlepage.class.getName());

    
    public Titlepage() {
        initComponents();
//       setExtendedState(JFrame.MAXIMIZED_BOTH);
//       setVisible(true
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        label2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AdminButton = new javax.swing.JButton();
        UserRegistrationButton = new javax.swing.JButton();
        UserLoginButton = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quote = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 204, 153));
        label2.setText("Ring || Earring || Necklace || Bracelet");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 480, 42));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminButton.setBackground(new java.awt.Color(0, 102, 102));
        AdminButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AdminButton.setForeground(new java.awt.Color(242, 242, 242));
        AdminButton.setText("Admin Login");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        UserRegistrationButton.setBackground(new java.awt.Color(0, 102, 102));
        UserRegistrationButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        UserRegistrationButton.setForeground(new java.awt.Color(242, 242, 242));
        UserRegistrationButton.setText("User Registration");
        UserRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRegistrationButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UserRegistrationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 200, 30));

        UserLoginButton.setBackground(new java.awt.Color(0, 102, 102));
        UserLoginButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        UserLoginButton.setForeground(new java.awt.Color(242, 242, 242));
        UserLoginButton.setText("User Login");
        UserLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UserLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 50));

        label1.setFont(new java.awt.Font("Book Antiqua", 3, 85)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 204, 0));
        label1.setText("DIVA'S ");
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 320, 60));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 3, 85)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("CREATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 470, 60));

        quote.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        quote.setForeground(new java.awt.Color(242, 242, 242));
        quote.setText("\"Not just jewellery, it’s a diva’s statement, Own your shine with Divas Creation.\"");
        getContentPane().add(quote, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 750, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jewellery (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1020, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLoginButtonActionPerformed
       new Login().setVisible(true);
    }//GEN-LAST:event_UserLoginButtonActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        new Adminlogin().setVisible(true);
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void UserRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRegistrationButtonActionPerformed
         new Register().setVisible(true);
    }//GEN-LAST:event_UserRegistrationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Titlepage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JButton UserLoginButton;
    private javax.swing.JButton UserRegistrationButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel quote;
    // End of variables declaration//GEN-END:variables
}
